### PR TITLE
Adding spanish names from the INE

### PR DESCRIPTION
**Pull request by Micosilent**
Added the dataset from the 5000 most frequent names for males and females from the Spanish institute of statistics.

They are currently ordered by frequency, all the males, and then all the females. If you wish instead to have them ordered alphabetically let me know and I will reorder them.

[ Data consulted 28/07/2023 at [https://www.ine.es/tnombres/inicio.do](https://www.ine.es/tnombres/inicio.do) ]

### CODE REVIEW

**Comment by DavideViolante** [comment]
Gracias!

**Comment by DavideViolante** [comment]
I just noticed there are some duplicates, we should remove them (in another PR)
Examples:
Andrea,
Juan
...

we should consider only the most "common" one, so Andrea and Juan should return male.
Sorting alphabetically we would have noticed it ealier.

@Micosilent

**Comment by Micosilent** [comment]
How open to changing the data structure of the name lists are you? If we remove duplicates we will have problems when a name is expected to return female in a language and male in another

```js

const genderEN = getGender('Andrea', 'en');
const genderIT = getGender('Andrea', 'it');

console.log(genderEN); // female
console.log(genderIT); // male

```

I propose moving from a map for each language, to having a map with all the names as keys, and values being an object with a languague key and a female/male value, i.e

```js
"andrea": { en: "female", it: "male", es: "female"}
```

If we order the languagues inside the object in order of frequency, when we get a function call without specifying the language `getGender('Andrea')`, we return the first key of the object, such as to return the gender of the most frequent language. Obtaining correlated frequency information in diferent languagues may probe difficult, so I propose maintaining the current language priority when building the map (en, it, es)

We can maintain the current function signature and returns, as to maintain backwards compatibility with current users

**Comment by DavideViolante** [comment]
That might work but I've to think about it. Meanwhile we should fix the duplicates and maintain the same map structure. I think the other languages have no duplicates at the moment.

**Pull request merged**
