### PR TITLE
Add french names

### PR DESCRIPTION
**Pull request by aymericDLB**

### CODE REVIEW

**Comment by DavideViolante** [comment]
Hello, thank you, where did you get the names list?

**Comment by aymericDLB** [comment]
> Hello, thank you, where did you get the names list?

Hello, I found this list on the website of the French government

**Comment by kartben** [comment]
This is great! However, the list as duplicate entries for names that are unisex (ex. Frederick). These duplicates should be removed so that `getGender()` returns unknown in case of such an ambiguity.

**Comment by kartben** [comment]
@aymericDLB would you be willing to share your script? I am willing to help clean things up. It looks like there are also duplicates due to entires that are just likely very wrong in the original dataset (ex. male named "Agnès"), so I would suggest to generate a list where: 
- duplicate name is dropped altogether when there seems to be clear ambiguity. Not sure what the threshold should be though. Dominique is 60/40, Claude 12/88, Camille 27/73,  ...
- when there is an overwhelming ratio (99.5%?) for a given gender, keep this one and drop the other.

**Comment by DavideViolante** [comment]
Hello @kartben , there is a issue about duplicates here https://github.com/DavideViolante/gender-detection-from-name/issues/80
Let's discuss there

**Pull request merged**
