### PR TITLE
adding french and a lot of langages in all from data.gouv.fr dataset

### PR DESCRIPTION
**Pull request by alumbo**

### CODE REVIEW

**Comment by DavideViolante** [comment]
This seems a nice source but the format of the new file should be like the other files (en.js, it.js) imho, not a CSV.
```js
const enNames = new Map([
  ['aabriella', 'female'],
  ['aadam', 'male'],
  ...
]);
```

**Comment by alumbo** [comment]
Yes I will send you another pull request with french at least. There is also an encoding issue with the CSV.
By the way shouldn't we return a different string when it's "unknow" because there is no result in database and when it's "unknow" because the name could be for male or female (in the same langage), like "Dominique" in french for example.

**Comment by DavideViolante** [comment]
I would return the most common one between male and female for names that are used for both genders. I'd prefer to prevent to return another string such as unisex, that is not giving exact info in return. This library goal is to assign an exact gender detected by the name, but for obvious reasons it could be wrong sometimes.

**Comment by DavideViolante** [comment]
Closing due to another PR added french.

**Pull request closed without merging**
